/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Usuario
 */
public class IntefazGrafica extends javax.swing.JFrame {

    private int valorComercial;
    private final double descuentoUno=0.1;
    private final double descuentoDos=0.2;
    private final double descuentoTres=0.4;
    private int opcion;
    /**
     * Creates new form IntefazGrafica
     */
    public IntefazGrafica() {
        initComponents();
        comboMarca.addItem("BMW");
        comboMarca.addItem("ASTON MARTIN");
        comboMarca.addItem("AUDI");
        
        
        comboLinea.addItem("Z4");
        comboLinea.addItem("Vantage V8");
        comboLinea.addItem("A4");
        
        comboModelo.addItem("2015");
        comboModelo.addItem("2016");
        comboModelo.addItem("2017");
        comboModelo.addItem("2018");
        comboModelo.addItem("2019");
        comboModelo.addItem("2020");
        comboModelo.addItem("2021");
       
    }

    public void setComboLinea(JComboBox<String> comboLinea) {
        this.comboLinea = comboLinea;
    }
    public void setComboMarca(JComboBox<String> comboMarca) {
        this.comboMarca = comboMarca;
    }
    public JComboBox<String> getComboLinea() {
        return comboLinea;
    }
    public JComboBox<String> getComboMarca() {
        return comboMarca;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboMarca = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboLinea = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        botonValorComercial = new javax.swing.JButton();
        comboModelo = new javax.swing.JComboBox<>();
        botonImpuesto = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Marca");

        comboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMarcaActionPerformed(evt);
            }
        });

        jLabel2.setText("Linea");

        jLabel3.setText("Modelo");

        botonValorComercial.setText("Valor Comercial");
        botonValorComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonValorComercialActionPerformed(evt);
            }
        });

        comboModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModeloActionPerformed(evt);
            }
        });

        botonImpuesto.setText("Impuesto");
        botonImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImpuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonImpuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonValorComercial)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonValorComercial)
                    .addComponent(botonImpuesto))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMarcaActionPerformed
    
    private void botonValorComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonValorComercialActionPerformed
 
       String m,l,año;
       int vComercial;

       String modeloString = (String) comboModelo.getSelectedItem();
       int modeloint = Integer.parseInt(modeloString);
       
        m = (String)comboMarca.getSelectedItem();
        l = (String)comboLinea.getSelectedItem();
        
        if("BMW".equals(m) && "Z4".equals(l) && modeloint>=2018){
            vComercial=25000;
            JOptionPane.showMessageDialog(null, "El valor comercial es: "+vComercial+" Dolares");
             valorComercial = vComercial;
        }
        else{
            if("BMW".equals(m) && "Z4".equals(l) && modeloint<2018){
              vComercial=20000;
              JOptionPane.showMessageDialog(null, "El valor comercial es: "+vComercial+" Dolares");
              valorComercial = vComercial;
            }
            else{
                if("ASTON MARTIN".equals(m) && "Vantage V8".equals(l) && modeloint>=2018){
                 vComercial=205000;
                 JOptionPane.showMessageDialog(null, "El valor comercial es: "+vComercial+" Dolares");
                 valorComercial = vComercial;
                }
                else{
                    if("ASTON MARTIN".equals(m) && "Vantage V8".equals(l) && modeloint<2018){
                    vComercial=160000;
                    JOptionPane.showMessageDialog(null, "El valor comercial es: "+vComercial+" Dolares");
                    valorComercial = vComercial;
                    }
                    else{
                        if("AUDI".equals(m) && "A4".equals(l) && modeloint>2018){
                            vComercial=26000;
                            JOptionPane.showMessageDialog(null, "El valor comercial es: "+vComercial+" Dolares");
                            valorComercial = vComercial;
                        }
                        else{
                            if("AUDI".equals(m) && "A4".equals(l) && modeloint<2018){
                               vComercial=14000;
                               JOptionPane.showMessageDialog(null, "El valor comercial es: "+vComercial+" Dolares");
                               valorComercial = vComercial;
                            }
                            
                            
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_botonValorComercialActionPerformed

    private void comboModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboModeloActionPerformed

    private void botonImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImpuestoActionPerformed
        double nuevoValor;
        if(valorComercial==25000 || valorComercial==20000 || valorComercial==205000 || valorComercial==160000 || valorComercial==26000 || valorComercial==14000)  {
          opcion=  Integer.parseInt(JOptionPane.showInputDialog(null,"Descuento por pronto pago"
                    + "\nDescuento por ser de servicio público"
                    + "\nDescuento por traslado de cuenta"
                  + "\nIngrese 1 si aplica al primer descuento o dos si aplica a los dos primeros o 3 si aplica a todos los descuentos"));
                    
            if(opcion == 1){
                
                nuevoValor = valorComercial - (valorComercial*descuentoUno);
                
                JOptionPane.showMessageDialog(null, "El impuesto es: "+nuevoValor
                        + "\nEl primer descuento aplicado es de un 10%");
            }
            if(opcion == 2){
                
                nuevoValor = valorComercial - (valorComercial*descuentoUno) - (valorComercial*descuentoDos);
                
                JOptionPane.showMessageDialog(null, "El impuesto es: "+nuevoValor
                        + "\nEl primer descuento aplicado es de un 10%"
                                + "\nEl segundo descuento aplicado es de un 20%");
            }
            if(opcion == 3){
                
                nuevoValor = valorComercial - (valorComercial*descuentoUno) - (valorComercial*descuentoDos) - (valorComercial*descuentoTres);
                
                JOptionPane.showMessageDialog(null, "El impuesto es: "+nuevoValor
                        + "\nEl primer descuento aplicado es de un 10%"
                                + "\nEl segundo descuento aplicado es de un 20%"
                                + "\nEl tercer descuento aplicado es de un 40%");
            }
            
            
        }
        
    }//GEN-LAST:event_botonImpuestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntefazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntefazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntefazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntefazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntefazGrafica().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonImpuesto;
    private javax.swing.JButton botonValorComercial;
    private javax.swing.JComboBox<String> comboLinea;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
